version: '3.9'


services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports: 
      - 5432:5432
  
  app:
    build:
      context: .
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers=2 --threads=4 --worker-class=gthread"
    expose:
      - 8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - DEBUG=${DEBUG}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NOTIF_EMAIL_ADDRESS=${NOTIF_EMAIL_ADDRESS}
      - NOTIF_PW=${NOTIF_PW}
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379