version: '5.0'

services:
  db:
    image: postgres:13-alpine
    container_name: kpk-app_db_1
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports: 
      - 5432:5432
  
  app_blue:
    build:
      context: .
    restart: always
    container_name: kpk-app_app_blue_1
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             sh /app/watch_and_reload.sh 8001"
    working_dir: /app
    expose:
      - 8001
    volumes:
      - ./app:/app:rw
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - DEBUG=${DEBUG}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NOTIF_EMAIL_ADDRESS=${NOTIF_EMAIL_ADDRESS}
      - NOTIF_PW=${NOTIF_PW}
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  app_green:
    build:
      context: .
    restart: always
    container_name: kpk-app_app_green_1
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             sh /app/watch_and_reload.sh 8002"
    working_dir: /app
    expose:
      - 8002
    volumes:
      - ./app:/app:rw
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - DEBUG=${DEBUG}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NOTIF_EMAIL_ADDRESS=${NOTIF_EMAIL_ADDRESS}
      - NOTIF_PW=${NOTIF_PW}
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: kpk-app_nginx_1
    ports:
      - 1337:80
    volumes:
      - ./app:/app
    depends_on:
      - app_blue

  redis:
    image: redis:alpine
    container_name: kpk-app_redis_1
    ports:
      - 6379:6379