# Generated by Django 3.2.18 on 2023-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecsheetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255)),
                ('po_number', models.CharField(max_length=255)),
                ('juliandate', models.CharField(max_length=255)),
                ('state_json', models.JSONField()),
            ],
        ),
    ]
