# Generated by Django 3.2.25 on 2025-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecountrecord',
            name='sage_converted_quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
