# Generated by Django 3.2.18 on 2023-04-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0002_specsheetstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specsheetstate',
            name='state_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
