# Generated by Django 3.2.17 on 2023-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0003_alter_specsheetstate_state_json'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specsheetstate',
            constraint=models.UniqueConstraint(fields=('item_code', 'po_number', 'juliandate'), name='unique_specsheet_state'),
        ),
    ]
