# Generated by Django 3.2.19 on 2023-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0004_specsheetstate_unique_specsheet_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('counted_date', models.DateField(blank=True, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('counted', models.BooleanField(default=False)),
                ('count_type', models.TextField(blank=True, null=True)),
                ('collection_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
