# Generated by Django 3.2.19 on 2023-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0005_prodcomponentcountrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(blank=True, null=True)),
                ('audit_group', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
