# Generated by Django 3.2.19 on 2023-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0006_auditgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecountrecord',
            name='counted_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
