# Generated by Django 3.2.19 on 2023-08-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0007_warehousecountrecord_counted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditGroup',
        ),
    ]
