# Generated by Django 3.2.20 on 2023-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0008_delete_auditgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecountrecord',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
