# Generated by Django 3.2.25 on 2024-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodverse', '0009_warehousecountrecord_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousecountrecord',
            name='containers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
