# Generated by Django 3.2.13 on 2022-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blendthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend', models.TextField(blank=True, null=True)),
                ('blend_description', models.TextField(blank=True, null=True)),
                ('starttime', models.TextField(blank=True, null=True)),
                ('line', models.TextField(blank=True, null=True)),
                ('oh_now', models.TextField(blank=True, null=True)),
                ('oh_during_run', models.TextField(blank=True, null=True)),
                ('qty_required', models.TextField(blank=True, null=True)),
                ('oh_after_run', models.TextField(blank=True, null=True)),
                ('one_week_short', models.TextField(blank=True, null=True)),
                ('two_week_short', models.TextField(blank=True, null=True)),
                ('three_week_short', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blendthese',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='lotnumbergenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lot_number', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotnumbergenerator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='checklistlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('operator_name', models.CharField(max_length=100, null=True)),
                ('unit_number', models.CharField(choices=[('17', '17'), ('6', '6')], max_length=3)),
                ('serial_number', models.CharField(max_length=100)),
                ('engine_oil_checked', models.BooleanField()),
                ('engine_oil_comments', models.TextField(blank=True)),
                ('propane_tank_checked', models.BooleanField()),
                ('propane_tank_comments', models.TextField(blank=True)),
                ('radiator_leaks_checked', models.BooleanField()),
                ('radiator_leaks_comments', models.TextField(blank=True)),
                ('tires_checked', models.BooleanField()),
                ('tires_comments', models.TextField(blank=True)),
                ('mast_forks_checked', models.BooleanField()),
                ('mast_forks_comments', models.TextField(blank=True)),
                ('leaks_checked', models.BooleanField()),
                ('leaks_comments', models.TextField(blank=True)),
                ('horn_checked', models.BooleanField()),
                ('horn_comments', models.TextField(blank=True)),
                ('driver_compartment_checked', models.BooleanField()),
                ('driver_compartment_comments', models.TextField(blank=True)),
                ('seatbelt_checked', models.BooleanField()),
                ('seatbelt_comments', models.TextField(blank=True)),
                ('battery_checked', models.BooleanField()),
                ('battery_comments', models.TextField(blank=True)),
                ('safety_equipment_checked', models.BooleanField()),
                ('safety_equipment_comments', models.TextField(blank=True)),
                ('steering_checked', models.BooleanField()),
                ('steering_comments', models.TextField(blank=True)),
                ('brakes_checked', models.BooleanField()),
                ('brakes_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
    ]
