# Generated by Django 3.2.13 on 2022-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lotnumexcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lot_number', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotnumexcel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='lotnumbergenerator',
        ),
    ]
