# Generated by Django 3.2.25 on 2025-06-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaChangeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_item_codes', models.JSONField(default=list, help_text='A list of item codes for blends whose formula is changing.')),
                ('ingredient_item_code', models.TextField(help_text='The ingredient that is changing in the formula.', unique=True)),
                ('notification_trigger_quantity', models.DecimalField(decimal_places=2, help_text='Inventory level of any parent_item_code at which to notify for change.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formula Change Alert',
                'verbose_name_plural': 'Formula Change Alerts',
            },
        ),
    ]
