# Generated by Django 3.2.19 on 2023-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(blank=True, null=True)),
                ('audit_group', models.TextField(blank=True, null=True)),
                ('group_type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlendingAuditGroup',
        ),
    ]
