# Generated by Django 3.2.25 on 2024-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('adp_employee_id', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=3)),
                ('punch_date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=4, max_digits=6)),
                ('pay_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
