# Generated by Django 3.2.19 on 2023-07-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendcomponentcountrecord',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
