# Generated by Django 3.2.25 on 2025-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HxDeskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('item_code', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=20)),
                ('blend_area', models.CharField(default='Hx_Desk', max_length=20)),
                ('tank', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
