# Generated by Django 3.2.23 on 2024-01-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatifproductionlinerun',
            old_name='relative_order',
            new_name='id2',
        ),
    ]
