# Generated by Django 3.2.20 on 2023-10-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueSheetNeeded',
        ),
    ]
