# Generated by Django 3.2.25 on 2025-05-15 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_username', models.CharField(blank=True, max_length=150, null=True)),
                ('tank_identifier', models.CharField(max_length=100)),
                ('item_code', models.TextField(blank=True, null=True)),
                ('start_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_gallons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gallons_dispensed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
