# Generated by Django 3.2.25 on 2025-10-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingalias',
            name='supply_type',
            field=models.CharField(choices=[('OPERATING', 'Operating Supplies'), ('IT', 'IT Supplies')], default='OPERATING', max_length=20),
        ),
    ]
