# Generated by Django 3.2.13 on 2022-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklistlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='DateTime')),
                ('operator_name', models.CharField(max_length=100, null=True)),
                ('unit_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('engine_oil_checked', models.BooleanField()),
                ('engine_oil_comments', models.TextField(blank=True)),
                ('propane_tank_checked', models.BooleanField()),
                ('propane_tank_comments', models.TextField(blank=True)),
                ('radiator_leaks_checked', models.BooleanField()),
                ('radiator_leaks_comments', models.TextField(blank=True)),
                ('tires_checked', models.BooleanField()),
                ('tires_comments', models.TextField(blank=True)),
                ('mast_forks_checked', models.BooleanField()),
                ('mast_forks_comments', models.TextField(blank=True)),
                ('leaks_checked', models.BooleanField()),
                ('leaks_comments', models.TextField(blank=True)),
                ('horn_checked', models.BooleanField()),
                ('horn_comments', models.TextField(blank=True)),
                ('driver_compartment_checked', models.BooleanField()),
                ('driver_compartment_comments', models.TextField(blank=True)),
                ('seatbelt_checked', models.BooleanField()),
                ('seatbelt_comments', models.TextField(blank=True)),
                ('battery_checked', models.BooleanField()),
                ('battery_comments', models.TextField(blank=True)),
                ('safety_equipment_checked', models.BooleanField()),
                ('safety_equipment_comments', models.TextField(blank=True)),
                ('steering_checked', models.BooleanField()),
                ('steering_comments', models.TextField(blank=True)),
                ('brakes_checked', models.BooleanField()),
                ('brakes_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
