# Generated by Django 3.2.13 on 2022-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_pn', models.TextField(blank=True, null=True)),
                ('blend_desc', models.TextField(blank=True, null=True)),
                ('starttime', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('expOH', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('count', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('count_date', models.DateField(blank=True, null=True)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
    ]
