# Generated by Django 3.2.16 on 2022-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_label', models.TextField()),
                ('fill_height', models.DecimalField(decimal_places=5, max_digits=50)),
                ('measuring_distance', models.DecimalField(decimal_places=5, max_digits=50)),
                ('distance_A', models.DecimalField(decimal_places=5, max_digits=50)),
                ('distance_B', models.DecimalField(decimal_places=5, max_digits=50)),
                ('scaled_volume', models.DecimalField(decimal_places=5, max_digits=50)),
                ('max_scaled_volume', models.DecimalField(decimal_places=5, max_digits=50)),
                ('percent_filled', models.DecimalField(decimal_places=5, max_digits=50)),
                ('gal_per_inch', models.DecimalField(decimal_places=5, max_digits=50)),
            ],
        ),
    ]
