# Generated by Django 3.2.13 on 2022-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotnumrecord',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
