# Generated by Django 3.2.25 on 2025-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendContainerClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(default='')),
                ('tote_classification', models.TextField(default='')),
                ('hose_color', models.TextField(default='')),
                ('tank_classification', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='ToteClassification',
        ),
    ]
