# Generated by Django 3.2.19 on 2023-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deskoneschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='desktwoschedule',
            options={},
        ),
        migrations.AlterField(
            model_name='deskoneschedule',
            name='order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='desktwoschedule',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
