# Generated by Django 3.2.23 on 2024-01-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendFormulaComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_reference_number', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('blend_number', models.TextField(blank=True, null=True)),
                ('product_density', models.FloatField(blank=True, null=True)),
                ('component_item_code', models.TextField(blank=True, null=True)),
                ('percent_weight_of_total', models.FloatField(blank=True, null=True)),
                ('sequence', models.FloatField(blank=True, null=True)),
                ('blend_instructions', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blend_formula_component',
                'managed': False,
            },
        ),
    ]
