# Generated by Django 3.2.19 on 2023-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRecordSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.TextField(blank=True, null=True)),
                ('count_type', models.TextField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blendcomponentcountrecord',
            name='counted_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blendcountrecord',
            name='counted_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
