# Generated by Django 3.2.25 on 2025-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotnumrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotnumrecord',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
