# Generated by Django 3.2.25 on 2025-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255)),
                ('vendor_part_number', models.CharField(max_length=255)),
                ('vendor_description', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('blending_notes', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='purchasing_item_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchasing Alias',
                'verbose_name_plural': 'Purchasing Aliases',
            },
        ),
    ]
