# Generated by Django 3.2.22 on 2023-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foamfactor',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='foamfactor',
            name='item_description',
        ),
        migrations.AddField(
            model_name='foamfactor',
            name='foam_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='foamfactor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
