# Generated by Django 3.2.25 on 2024-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HxBlendthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(blank=True, null=True)),
                ('po_number', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('amt', models.BigIntegerField(blank=True, null=True)),
                ('component_item_code', models.TextField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('prod_line', models.TextField(blank=True, null=True)),
                ('item_run_qty', models.BigIntegerField(blank=True, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('id2', models.BigIntegerField(blank=True, null=True)),
                ('component_item_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hx_blendthese',
                'managed': False,
            },
        ),
    ]
