# Generated by Django 3.2.23 on 2024-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendTankRestriction',
            fields=[
                ('item_code', models.TextField(db_column='ItemCode', primary_key=True, serialize=False)),
                ('range_one_minimum', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True)),
                ('range_one_maximum', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True)),
                ('range_two_minimum', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True)),
                ('range_two_maximum', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='BlendProtection',
        ),
    ]
