# Generated by Django 3.2.13 on 2022-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220428_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='lotnumrecords',
            fields=[
                ('part_number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lot_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
