# Generated by Django 3.2.13 on 2022-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checklistlog_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='unit_number',
            field=models.CharField(choices=[('17', 'Seventeen'), ('6', 'Six')], max_length=3),
        ),
    ]
