# Generated by Django 3.2.23 on 2024-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blendformulacomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendinstruction',
            name='component_item_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
