# Generated by Django 3.2.25 on 2026-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blendcontainerclassification_flush_tote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendcontainerclassification',
            name='flush_tote',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
