# Generated by Django 3.2.25 on 2025-05-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_tankusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendSheetPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('details_at_print_time', models.JSONField(default=dict)),
                ('lot_num_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotnumrecord')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-printed_at'],
            },
        ),
    ]
