# Generated by Django 3.2.22 on 2023-11-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231114_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foamfactor',
            old_name='foam_factor',
            new_name='factor',
        ),
        migrations.AddField(
            model_name='foamfactor',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
