# Generated by Django 3.2.19 on 2023-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blendcountrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendcountrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
