# Generated by Django 3.2.25 on 2025-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchasingalias_supply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingalias',
            name='supply_type',
            field=models.CharField(choices=[('OPERATING', 'Blending Supplies'), ('IT', 'IT Supplies')], default='OPERATING', max_length=20),
        ),
    ]
