# Generated by Django 3.2.19 on 2023-08-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230824_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditgroup',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
