# Generated by Django 3.2.19 on 2023-07-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blendcomponentcountrecord_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendcomponentcountrecord',
            name='test',
        ),
    ]
