# Generated by Django 3.2.25 on 2025-11-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manualgauge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualgauge',
            options={'db_table': 'manual_gauge', 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='manualgauge',
            name='tank_label_kpk',
            field=models.TextField(db_column='tank_label_KPK'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE manual_gauge DROP CONSTRAINT IF EXISTS manual_gauge_tank_label_KPK_key;",
            reverse_sql="ALTER TABLE manual_gauge ADD CONSTRAINT manual_gauge_tank_label_KPK_key UNIQUE (\"tank_label_KPK\");",
        ),
    ]
