# Generated by Django 3.2.19 on 2023-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230627_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskoneschedule',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desktwoschedule',
            name='order',
            field=models.IntegerField(),
        ),
    ]
