# Generated by Django 3.2.22 on 2023-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_foamfactor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHSPictogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default=None, max_length=100)),
                ('item_description', models.CharField(default=None, max_length=100)),
                ('image_reference', models.ImageField(default=None, upload_to='core/media/GHSPictograms/')),
            ],
        ),
    ]
