# Generated by Django 3.2.25 on 2024-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hxblendthese'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcollectionlink',
            name='id_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
