# Generated by Django 3.2.25 on 2024-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241106_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='absent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='excused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='tardy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
