# Generated by Django 3.2.25 on 2024-08-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_countcollectionlink_id_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countcollectionlink',
            old_name='collection_link',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='countcollectionlink',
            old_name='id_list',
            new_name='count_id_list',
        ),
    ]
