# Generated by Django 3.2.25 on 2025-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blendsheetprintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotnumrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lotnumrecord',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
