# Generated by Django 3.2.13 on 2022-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220421_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistlog',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='checklistlog',
            name='unit_number',
            field=models.CharField(choices=[('17', '17'), ('6', '6')], max_length=3),
        ),
    ]
