# Generated by Django 3.2.19 on 2023-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_blendcomponentcountrecord_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCollectionLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.TextField(blank=True, null=True)),
                ('collection_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
