# Generated by Django 3.2.25 on 2025-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_purchasingalias_supply_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualGauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_label_kpk', models.TextField(db_column='tank_label_KPK', unique=True)),
                ('dead_space', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('full_space', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manual_gauge',
                'ordering': ['tank_label_kpk'],
            },
        ),
    ]
