# Generated by Django 3.2.13 on 2022-04-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lotnumrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lotnumrecords',
            new_name='lotnumrecord',
        ),
    ]
