# Generated by Django 3.2.23 on 2024-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blendinstruction_component_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.TextField()),
                ('fill_percentage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fill_height_inches', models.DecimalField(decimal_places=2, max_digits=50)),
                ('height_capacity_inches', models.DecimalField(decimal_places=2, max_digits=50)),
                ('filled_gallons', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='TankLevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log', models.JSONField()),
            ],
        ),
    ]
