# Generated by Django 3.2.25 on 2026-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tankcontrollimits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImItemTransactionHistoryDeeptime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('itemcode', models.TextField(blank=True, null=True)),
                ('warehousecode', models.TextField(blank=True, null=True)),
                ('transactiondate', models.DateField(blank=True, null=True)),
                ('transactioncode', models.TextField(blank=True, null=True)),
                ('entryno', models.TextField(blank=True, null=True)),
                ('sequenceno', models.TextField(blank=True, null=True)),
                ('imtransactionentrycomment', models.TextField(blank=True, null=True)),
                ('apdivisionno', models.TextField(blank=True, null=True)),
                ('vendorno', models.TextField(blank=True, null=True)),
                ('ardivisionno', models.TextField(blank=True, null=True)),
                ('customerno', models.TextField(blank=True, null=True)),
                ('referencedate', models.DateField(blank=True, null=True)),
                ('fiscalcalyear', models.TextField(blank=True, null=True)),
                ('fiscalcalperiod', models.TextField(blank=True, null=True)),
                ('shiptocode', models.TextField(blank=True, null=True)),
                ('invoicetype', models.TextField(blank=True, null=True)),
                ('transactionqty', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('unitcost', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('allocatedcost', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('unitprice', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('extendedprice', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('extendedcost', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('extendedstandardcost', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('dateupdated', models.DateField(blank=True, null=True)),
                ('timeupdated', models.TextField(blank=True, null=True)),
                ('userupdatedkey', models.TextField(blank=True, null=True)),
                ('invoicehistoryheaderseqno', models.TextField(blank=True, null=True)),
                ('receipthistoryheaderseqno', models.TextField(blank=True, null=True)),
                ('receipthistorypurchaseorderno', models.TextField(blank=True, null=True)),
                ('sourcejournal', models.TextField(blank=True, null=True)),
                ('journalnoglbatchno', models.TextField(blank=True, null=True)),
                ('workticketkey', models.TextField(blank=True, null=True)),
                ('workticketno', models.TextField(blank=True, null=True)),
                ('workticketdesc', models.TextField(blank=True, null=True)),
                ('workticketlinekey', models.TextField(blank=True, null=True)),
                ('workticketstepno', models.TextField(blank=True, null=True)),
                ('workticketclasscode', models.TextField(blank=True, null=True)),
                ('activitycode', models.TextField(blank=True, null=True)),
                ('workcenter', models.TextField(blank=True, null=True)),
                ('toolcode', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_itemtransactionhistory_deeptime',
                'managed': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='tankcontrollimits',
            name='core_tankco_tank_na_4c6a77_idx',
        ),
        migrations.AddIndex(
            model_name='tankcontrollimits',
            index=models.Index(fields=['tank_name', '-calculated_at'], name='core_tankco_tank_na_077506_idx'),
        ),
    ]
