# Generated by Django 3.2.25 on 2025-11-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manualgauge_history_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualgauge',
            name='recorded_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RemoveField(
            model_name='manualgauge',
            name='updated_at',
        ),
    ]
