# Generated by Django 3.2.23 on 2024-01-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tanklevel_tanklevellog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanklevel',
            options={'managed': False},
        ),
    ]
