# Generated by Django 3.2.25 on 2024-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241106_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
