# Generated by Django 3.2.25 on 2024-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240829_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcollectionlink',
            name='record_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
