# Generated by Django 3.2.13 on 2022-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_lotnumrecords_lotnumrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotnumrecord',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
