# Generated by Django 3.2.25 on 2024-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_popurchaseorderheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialContainerLabelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.TextField(blank=True, null=True)),
                ('log_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
