# Generated by Django 3.2.25 on 2025-10-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manualgauge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualgauge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
