# Generated by Django 3.2.19 on 2023-07-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_countcollectionlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountCollectionLinks',
            new_name='CountCollectionLink',
        ),
    ]
