# Generated by Django 3.2.25 on 2024-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partialcontainerlabellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcollectionlink',
            name='link_order',
            field=models.IntegerField(default=0),
        ),
    ]
