# Generated by Django 3.2.25 on 2024-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241106_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='absent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='excused',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='tardy',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
