# Generated by Django 3.2.25 on 2024-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_countcollectionlink_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countcollectionlink',
            name='count_id_list',
            field=models.JSONField(default=list),
        ),
    ]
