# Generated by Django 3.2.25 on 2026-01-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_discharge_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargetestingrecord',
            name='sampling_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_tests_sampling', to=settings.AUTH_USER_MODEL),
        ),
    ]
