# Generated by Django 3.2.13 on 2022-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blendinstruction_bmbilldetail_bmbillheader_ciitem_imitemcost_imitemtransactionhistory_imitemwarehous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lotnumexcel',
        ),
        migrations.AlterField(
            model_name='lotnumrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
