# Generated by Django 3.2.25 on 2024-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_countcollectionlink_link_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskoneschedule',
            name='tank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desktwoschedule',
            name='tank',
            field=models.TextField(blank=True, null=True),
        ),
    ]
