# Generated by Django 3.2.13 on 2022-05-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220509_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotnumrecord',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
