# Generated by Django 3.2.25 on 2024-06-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240604_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlendThese',
        ),
    ]
