# Generated by Django 3.2.25 on 2026-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dischargetestingrecord_sampling_personnel'),
    ]
