# Generated by Django 3.2.25 on 2026-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dischargetestingrecord_discharge_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargetestingrecord',
            name='ph_active_component',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
