# Generated by Django 3.2.25 on 2026-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dischargetestingrecord_ph_active_component'),
    ]