# Generated by Django 3.2.25 on 2026-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dischargetestingrecord_discharge_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcollectionlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
