# Generated by Django 3.2.25 on 2026-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_countcollectionlink_created_at'),
    ]

