# Generated by Django 3.2.25 on 2026-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_countcollectionlink_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargetestingrecord',
            name='discharge_material_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
