# Generated by Codex on 2026-02-05

from django.db import migrations, models


def _get_user_display(user):
    if not user:
        return None
    full_name = ""
    get_full_name = getattr(user, "get_full_name", None)
    if callable(get_full_name):
        full_name = (get_full_name() or "").strip()
    if full_name:
        return full_name
    username = getattr(user, "username", None)
    if username:
        username = str(username).strip()
        if username:
            return username
    email = getattr(user, "email", None)
    if email:
        email = str(email).strip()
        if email:
            return email
    return None


def forwards(apps, schema_editor):
    DischargeTestingRecord = apps.get_model("core", "DischargeTestingRecord")

    for record in (
        DischargeTestingRecord.objects.select_related("sampling_personnel").all().iterator()
    ):
        display = _get_user_display(record.sampling_personnel)
        if display:
            record.sampling_personnel_name = display
            record.save(update_fields=["sampling_personnel_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_dischargetestingrecord_discharge_material_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="dischargetestingrecord",
            name="sampling_personnel_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="dischargetestingrecord",
            name="sampling_personnel",
        ),
    ]
