# Generated by Django 3.2.25 on 2026-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dischargetestingrecord_discharge_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargetestingrecord',
            name='discharge_material_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
