# Generated by Django 3.2.25 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sampling_personnel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargetestingrecord',
            name='final_disposition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
