# Generated by Django 3.2.25 on 2026-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_dischargetestingrecord_final_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendcontainerclassification',
            name='waste_rag',
            field=models.TextField(blank=True, choices=[('', ''), ('Acids', 'Acids'), ('Flammables', 'Flammables'), ('Grease/Oil', 'Grease/Oil'), ('Soaps', 'Soaps'), ('Bleach', 'Bleach')], default=''),
        ),
    ]
