# Generated by Django 3.2.25 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blendcontainerclassification_waste_rag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendcontainerclassification',
            name='waste_rag',
            field=models.TextField(blank=True, choices=[('', ''), ('Acid', 'Acid'), ('Flammable', 'Flammable'), ('Grease/Oil', 'Grease/Oil'), ('Soap', 'Soap'), ('Base', 'Base')], default=''),
        ),
    ]
