# Generated by Django 3.2.25 on 2026-02-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_blendcontainerclassification_waste_rag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=30)),
                ('po_number', models.CharField(blank=True, default='', max_length=30)),
                ('product_description', models.CharField(blank=True, default='', max_length=255)),
                ('blend', models.CharField(blank=True, default='', max_length=255)),
                ('case_size', models.CharField(blank=True, default='', max_length=50)),
                ('scheduled_qty', models.IntegerField(blank=True, null=True)),
                ('produced_qty', models.IntegerField()),
                ('bottle', models.CharField(blank=True, default='', max_length=100)),
                ('cap', models.CharField(blank=True, default='', max_length=100)),
                ('runtime_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('carton', models.CharField(blank=True, default='', max_length=50)),
                ('pallet', models.CharField(blank=True, default='', max_length=50)),
                ('po_due_date', models.CharField(blank=True, default='', max_length=20)),
                ('line_name', models.CharField(max_length=50)),
                ('run_date', models.DateField()),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('num_employees', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_productionhistory',
                'ordering': ['-run_date', '-created_at'],
            },
        ),
    ]
