# Generated by Django 3.2.25 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_production_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='countcollectionlink',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
