# Generated by Django 3.2.25 on 2026-02-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_countcollectionlink_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countcollectionlink',
            old_name='is_hidden',
            new_name='is_archived',
        ),
    ]
