docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select * from core_lotnumrecord limit 5" 
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select COUNT(*) from core_lotnumrecord"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select * from core_blendinstruction limit 5"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select COUNT(*) from core_blendinstruction"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select * from core_foamfactor limit 5"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select COUNT(*) from core_foamfactor"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select * from core_forklift limit 5"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select COUNT(*) from core_forklift"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select * from core_countrecord limit 5"
docker exec -it kpk-app_app_1 python manage.py dbshell -- -c "select COUNT(*) from core_countrecord"