from rest_framework import serializers

from .models import ChecklistLogForm,LotNumRecordForm,ChecklistLog,BlendThese,LotNumRecord,BlendInstruction,PoPurchaseOrderDetail,ImItemWarehouse,ImItemTransactionHistory,ImItemCost,CiItem,BmBillHeader,BmBillDetail
   
class BlendInstructionSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BlendInstruction
        fields = ('bill_no',
                    'status',
                    'step_no',
                    'step_desc',
                    'component_code',
                    'component_desc',
                    )

class BlendTheseSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BlendThese
        fields = ('blend',
                    'blend_description',
                    'starttime',
                    'line',
                    'oh_now',
                    'oh_during_run',
                    'qty_required',
                    'oh_after_run',
                    'one_week_short',
                    'two_week_short',
                    'three_week_short',
                    )

class BmBillDetailSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BmBillDetail
        field = ('billno',
                    'revision',
                    'linekey',
                    'lineseqno',
                    'componentitemcode',
                    'componentrevision',
                    'itemtype',
                    'componentdesc',
                    'engineeringdrawingfindno',
                    'engineeringchangeaddno',
                    'engineeringchangeadddate',
                    'engineeringchangedelno',
                    'engineeringchangedeldate',
                    'workorderstepno',
                    'billtype',
                    'commenttext',
                    'miscchargeglacctkey',
                    'setupcharge',
                    'unitofmeasure',
                    'quantityperbill',
                    'standardunitcost',
                    'scrappercent',
                    'workticketstepno'
                    )

class BmBillHeaderSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BmBillHeader
        fields = ('billno',
                    'revision',
                    'billtype',
                    'drawingno',
                    'drawingrevision',
                    'datelastused',
                    'routingno',
                    'billhasoptions',
                    'currentbillrevision',
                    'optioninteractions',
                    'optioncategories',
                    'printcomponentdetail',
                    'maximumlotsize',
                    'yieldpercent',
                    'billdesc1',
                    'billdesc2',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'templateno',
                    'templaterevisionno'
                    )

class ChecklistLogSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ChecklistLog
        fields = ('date',
                    'operator_name',
                    'unit_number',
                    'serial_number',
                    'engine_oil_checked',
                    'engine_oil_comments',
                    'propane_tank_checked',
                    'propane_tank_comments',
                    'radiator_leaks_checked',
                    'radiator_leaks_comments',
                    'tires_checked',
                    'tires_comments',
                    'mast_forks_checked',
                    'mast_forks_comments',
                    'leaks_checked',
                    'leaks_comments',
                    'horn_checked',
                    'horn_comments',
                    'driver_compartment_checked',
                    'driver_compartment_comments',
                    'seatbelt_checked',
                    'seatbelt_comments',
                    'battery_checked',
                    'battery_comments',
                    'safety_equipment_checked',
                    'safety_equipment_comments',
                    'steering_checked',
                    'steering_comments',
                    'brakes_checked',
                    'brakes_comments'
                    )

class CiItemSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CiItem
        fields = ('itemcode',
                    'itemtype',
                    'itemcodedesc',
                    'extendeddescriptionkey',
                    'useinar',
                    'useinso',
                    'useinpo',
                    'useinbm',
                    'calculatecommission',
                    'dropship',
                    'ebmenabled',
                    'pricecode',
                    'printreceiptlabels',
                    'allocatelandedcost',
                    'warrantycode',
                    'salesunitofmeasure',
                    'purchaseunitofmeasure',
                    'standardunitofmeasure',
                    'posttoglbydivision',
                    'salesacctkey',
                    'costofgoodssoldacctkey',
                    'inventoryacctkey',
                    'purchaseacctkey',
                    'manufacturingcostacctkey',
                    'taxclass',
                    'purchasestaxclass',
                    'productline',
                    'producttype',
                    'valuation',
                    'defaultwarehousecode',
                    'primaryapdivisionno',
                    'primaryvendorno',
                    'imagefile',
                    'category1',
                    'category2',
                    'category3',
                    'category4',
                    'explodekititems',
                    'shipweight',
                    'commenttext',
                    'restockingmethod',
                    'standardunitcost',
                    'standardunitprice',
                    'commissionrate',
                    'basecommamt',
                    'purchaseumconvfctr',
                    'salesumconvfctr',
                    'volume',
                    'restockingcharge',
                    'procurementtype',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'allowbackorders',
                    'allowreturns',
                    'allowtradediscount',
                    'confirmcostincrinrcptofgoods',
                    'lastsolddate',
                    'lastreceiptdate',
                    'salespromotioncode',
                    'salestartingdate',
                    'saleendingdate',
                    'salemethod',
                    'nextlotserialno',
                    'inventorycycle',
                    'routingno',
                    'plannercode',
                    'buyercode',
                    'lowlevelcode',
                    'plannedbymrp',
                    'vendoritemcode',
                    'setupcharge',
                    'attachmentfilename',
                    'itemimagewidthinpixels',
                    'itemimageheightinpixels',
                    'lasttotalunitcost',
                    'averageunitcost',
                    'salespromotionprice',
                    'suggestedretailprice',
                    'salespromotiondiscountpercent',
                    'totalquantityonhand',
                    'averagebackorderfilldays',
                    'lastallocatedunitcost',
                    'totalinventoryvalue',
                    'inactiveitem',
                    'lastphysicalcountdate',
                    'commoditycode',
                    'templateno',
                    'tracklotserialexpirationdates',
                    'requireexpirationdate',
                    'calculateexpdatebasedon',
                    'numberuntilexpiration',
                    'calculatesellbybasedon',
                    'numbertosellbybefore',
                    'numbertosellbyafter',
                    'calculateusebybasedon',
                    'numbertousebybefore',
                    'numbertousebyafter',
                    'calculatereturnsbasedon',
                    'numbertoreturnafter'
                    )

class ImItemCostSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemCost
        fields = ('itemcode',
                    'warehousecode',
                    'tiertype',
                    'groupsort',
                    'receiptdate',
                    'receiptno',
                    'lotserialno',
                    'unitcost',
                    'quantityonhand',
                    'quantitycommitted',
                    'allocatedcost',
                    'transactiondate',
                    'negativeqty',
                    'tiergroup',
                    'extendedcost',
                    'costcalcqtycommitted',
                    'costcalccostcommitted',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'lotserialexpirationdate'
                    )

class ImItemTransactionHistorySerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemTransactionHistory
        fields = ('itemcode',
                    'warehousecode',
                    'transactiondate',
                    'transactioncode',
                    'entryno',
                    'sequenceno',
                    'imtransactionentrycomment',
                    'apdivisionno',
                    'vendorno',
                    'ardivisionno',
                    'customerno',
                    'referencedate',
                    'fiscalcalyear',
                    'fiscalcalperiod',
                    'shiptocode',
                    'invoicetype',
                    'transactionqty',
                    'unitcost',
                    'allocatedcost',
                    'unitprice',
                    'extendedprice',
                    'extendedcost',
                    'extendedstandardcost',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'invoicehistoryheaderseqno',
                    'receipthistoryheaderseqno',
                    'receipthistorypurchaseorderno',
                    'sourcejournal',
                    'journalnoglbatchno',
                    'workticketkey',
                    'workticketno',
                    'workticketdesc',
                    'workticketlinekey',
                    'workticketstepno',
                    'workticketclasscode',
                    'activitycode',
                    'workcenter',
                    'toolcode'
                    )

class ImItemWarehouseSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemWarehouse
        fields = ('itemcode',
                    'warehousecode',
                    'binlocation',
                    'reordermethod',
                    'quantityonhand',
                    'quantityonpurchaseorder',
                    'quantityonsalesorder',
                    'quantityonbackorder',
                    'averagecost',
                    'quantityrequiredforwo',
                    'economicorderqty',
                    'reorderpointqty',
                    'minimumorderqty',
                    'maximumonhandqty',
                    'quantityonworkorder',
                    'quantityinshipping',
                    'totalwarehousevalue',
                    'costcalcqtycommitted',
                    'costcalccostcommitted',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'lastphysicalcountdate'
                    )

class LotNumRecordSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = LotNumRecord
        fields = ('part_number',
                    'description',
                    'lot_number',
                    'quantity',
                    'date'
                    )

class PoPurchaseOrderDetailSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = PoPurchaseOrderDetail
        fields =('purchaseorderno',
                    'linekey',
                    'lineseqno',
                    'itemcode',
                    'extendeddescriptionkey',
                    'itemtype',
                    'itemcodedesc',
                    'usetax',
                    'requireddate',
                    'vendorpricecode',
                    'purchasesacctkey',
                    'valuation',
                    'unitofmeasure',
                    'warehousecode',
                    'productline',
                    'masterlinekey',
                    'reschedule',
                    'jobno',
                    'costcode',
                    'costtype',
                    'receiptofgoodsupdated',
                    'workorderno',
                    'stepno',
                    'substepprefix',
                    'substepsuffix',
                    'workordertype',
                    'allocatelandedcost',
                    'vendoraliasitemno',
                    'taxclass',
                    'commenttext',
                    'assetaccount',
                    'assettemplate',
                    'weightreference',
                    'weight',
                    'quantityordered',
                    'quantityreceived',
                    'quantitybackordered',
                    'masteroriginalqty',
                    'masterqtybalance',
                    'masterqtyorderedtodate',
                    'quantityinvoiced',
                    'unitcost',
                    'originalunitcost',
                    'extensionamt',
                    'receivedamt',
                    'invoicedamt',
                    'unitofmeasureconvfactor',
                    'receivedallocatedamt',
                    'invoicedallocatedamt',
                    'salesorderno',
                    'customerpono',
                    'purchaseorderhistorydtlseqno',
                    'workticketkey',
                    'workticketsteplinekey',
                    'workticketlinekey',
                    'workticketstatus'
                    )