from rest_framework import serializers
from .models import *


class BillOfMaterialsSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BillOfMaterials
        fields =('item_code',
                    'billdesc1',
                    'componentitemcode',
                    'itemcodedesc',
                    'quantityperbill',
                    'scrappercent',
                    'procurementtype',
                    'standardunitofmeasure',
                    'commenttext'        
                    )

class CountRecordSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CountRecord
        fields = ('part_number',
                    'part_description',
                    'starttime',
                    'expOH',
                    'count',
                    'count_date',
                    'difference',
                    )

class BlendInstructionSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BlendInstruction
        fields = ('step_no',
                    'step_desc',
                    'component_item_code',
                    'blend_part_num',
                    'ref_no',
                    'prepared_by',
                    'prepared_date',
                    'lbs_per_gal',
                    )

class BlendTheseSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BlendThese
        fields = ('bill_no',
                    'blend_pn',
                    'blend_desc',
                    'adjustedrunqty',
                    'qtyonhand',
                    'starttime',
                    'prodline',
                    'oh_after_run',
                    'week_calc',
                    'one_wk_short',
                    'two_wk_short',
                    'three_wk_short',
                    )

class BmBillDetailSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BmBillDetail
        field = ('billno',
                    'revision',
                    'linekey',
                    'lineseqno',
                    'componentitemcode',
                    'componentrevision',
                    'itemtype',
                    'componentdesc',
                    'engineeringdrawingfindno',
                    'engineeringchangeaddno',
                    'engineeringchangeadddate',
                    'engineeringchangedelno',
                    'engineeringchangedeldate',
                    'workorderstepno',
                    'billtype',
                    'commenttext',
                    'miscchargeglacctkey',
                    'setupcharge',
                    'unitofmeasure',
                    'quantityperbill',
                    'standardunitcost',
                    'scrappercent',
                    'workticketstepno'
                    )

class BmBillHeaderSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BmBillHeader
        fields = ('billno',
                    'revision',
                    'billtype',
                    'drawingno',
                    'drawingrevision',
                    'datelastused',
                    'routingno',
                    'billhasoptions',
                    'currentbillrevision',
                    'optioninteractions',
                    'optioncategories',
                    'printcomponentdetail',
                    'maximumlotsize',
                    'yieldpercent',
                    'billdesc1',
                    'billdesc2',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'templateno',
                    'templaterevisionno'
                    )

class ChecklistSubmissionTrackerSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ChecklistSubmissionRecord
        fields = ('check_date', 
                'forklift_1', 
                'forklift_2', 
                'forklift_3', 
                'forklift_4', 
                'forklift_5', 
                'forklift_6', 
                'forklift_7', 
                'forklift_8', 
                'forklift_9', 
                'forklift_10',
                'forklift_11',
                'forklift_12',
                'forklift_13',
                'forklift_15',
                'forklift_16',
                'forklift_17',
                'forklift_18',
                'forklift_19',
                'forklift_20',
                'forklift_21',
                'forklift_22',
                'forklift_22',
                'forklift_23',
                'forklift_23',
                'forklift_24',
                'forklift_25',
                'forklift_26',
                'forklift_27',
                'forklift_28',
                'forklift_29',
                'forklift_30',
                'forklift_32',
                'forklift_34',
                'forklift_35',
                'forklift_36',
                'forklift_37',
                'forklift_38',
                'forklift_39',
                'forklift_40',
                'forklift_41',
                'forklift_42',
                'forklift_43',
                'forklift_44',
                'forklift_45',
                'forklift_46',
                'forklift_47',
                'forklift_48',
                'forklift_49',
                'forklift_50',
                'forklift_Rental1',
                'forklift_Rental2',
                'forklift_Rental3',
                )

class ChecklistLogSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ChecklistLog
        fields = ('submitted_date',
                    'operator_name',
                    'unit_number',
                    'serial_number',
                    'engine_oil',
                    'engine_oil_comments',
                    'propane_tank',
                    'propane_tank_comments',
                    'radiator_leaks',
                    'radiator_leaks_comments',
                    'tires',
                    'tires_comments',
                    'mast_and_forks',
                    'mast_and_forks_comments',
                    'leaks',
                    'leaks_comments',
                    'horn',
                    'horn_comments',
                    'driver_compartment',
                    'driver_compartment_comments',
                    'seatbelt',
                    'seatbelt_comments',
                    'battery',
                    'battery_comments',
                    'safety_equipment',
                    'safety_equipment_comments',
                    'steering',
                    'steering_comments',
                    'brakes',
                    'brakes_comments'
                    )

class CiItemSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = CiItem
        fields = ('itemcode',
                    'itemtype',
                    'itemcodedesc',
                    'extendeddescriptionkey',
                    'useinar',
                    'useinso',
                    'useinpo',
                    'useinbm',
                    'calculatecommission',
                    'dropship',
                    'ebmenabled',
                    'pricecode',
                    'printreceiptlabels',
                    'allocatelandedcost',
                    'warrantycode',
                    'salesunitofmeasure',
                    'purchaseunitofmeasure',
                    'standardunitofmeasure',
                    'posttoglbydivision',
                    'salesacctkey',
                    'costofgoodssoldacctkey',
                    'inventoryacctkey',
                    'purchaseacctkey',
                    'manufacturingcostacctkey',
                    'taxclass',
                    'purchasestaxclass',
                    'productline',
                    'producttype',
                    'valuation',
                    'defaultwarehousecode',
                    'primaryapdivisionno',
                    'primaryvendorno',
                    'imagefile',
                    'category1',
                    'category2',
                    'category3',
                    'category4',
                    'explodekititems',
                    'shipweight',
                    'commenttext',
                    'restockingmethod',
                    'standardunitcost',
                    'standardunitprice',
                    'commissionrate',
                    'basecommamt',
                    'purchaseumconvfctr',
                    'salesumconvfctr',
                    'volume',
                    'restockingcharge',
                    'procurementtype',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'allowbackorders',
                    'allowreturns',
                    'allowtradediscount',
                    'confirmcostincrinrcptofgoods',
                    'lastsolddate',
                    'lastreceiptdate',
                    'salespromotioncode',
                    'salestartingdate',
                    'saleendingdate',
                    'salemethod',
                    'nextlotserialno',
                    'inventorycycle',
                    'routingno',
                    'plannercode',
                    'buyercode',
                    'lowlevelcode',
                    'plannedbymrp',
                    'vendoritemcode',
                    'setupcharge',
                    'attachmentfilename',
                    'itemimagewidthinpixels',
                    'itemimageheightinpixels',
                    'lasttotalunitcost',
                    'averageunitcost',
                    'salespromotionprice',
                    'suggestedretailprice',
                    'salespromotiondiscountpercent',
                    'totalquantityonhand',
                    'averagebackorderfilldays',
                    'lastallocatedunitcost',
                    'totalinventoryvalue',
                    'inactiveitem',
                    'lastphysicalcountdate',
                    'commoditycode',
                    'templateno',
                    'tracklotserialexpirationdates',
                    'requireexpirationdate',
                    'calculateexpdatebasedon',
                    'numberuntilexpiration',
                    'calculatesellbybasedon',
                    'numbertosellbybefore',
                    'numbertosellbyafter',
                    'calculateusebybasedon',
                    'numbertousebybefore',
                    'numbertousebyafter',
                    'calculatereturnsbasedon',
                    'numbertoreturnafter'
                    )

class ImItemCostSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemCost
        fields = ('itemcode',
                    'warehousecode',
                    'tiertype',
                    'groupsort',
                    'receiptdate',
                    'receiptno',
                    'lotserialno',
                    'unitcost',
                    'quantityonhand',
                    'quantitycommitted',
                    'allocatedcost',
                    'transactiondate',
                    'negativeqty',
                    'tiergroup',
                    'extendedcost',
                    'costcalcqtycommitted',
                    'costcalccostcommitted',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'lotserialexpirationdate'
                    )

class ImItemTransactionHistorySerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemTransactionHistory
        fields = ('itemcode',
                    'warehousecode',
                    'transactiondate',
                    'transactioncode',
                    'entryno',
                    'sequenceno',
                    'imtransactionentrycomment',
                    'apdivisionno',
                    'vendorno',
                    'ardivisionno',
                    'customerno',
                    'referencedate',
                    'fiscalcalyear',
                    'fiscalcalperiod',
                    'shiptocode',
                    'invoicetype',
                    'transactionqty',
                    'unitcost',
                    'allocatedcost',
                    'unitprice',
                    'extendedprice',
                    'extendedcost',
                    'extendedstandardcost',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'invoicehistoryheaderseqno',
                    'receipthistoryheaderseqno',
                    'receipthistorypurchaseorderno',
                    'sourcejournal',
                    'journalnoglbatchno',
                    'workticketkey',
                    'workticketno',
                    'workticketdesc',
                    'workticketlinekey',
                    'workticketstepno',
                    'workticketclasscode',
                    'activitycode',
                    'workcenter',
                    'toolcode'
                    )

class ImItemWarehouseSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = ImItemWarehouse
        fields = ('itemcode',
                    'warehousecode',
                    'binlocation',
                    'reordermethod',
                    'quantityonhand',
                    'quantityonpurchaseorder',
                    'quantityonsalesorder',
                    'quantityonbackorder',
                    'averagecost',
                    'quantityrequiredforwo',
                    'economicorderqty',
                    'reorderpointqty',
                    'minimumorderqty',
                    'maximumonhandqty',
                    'quantityonworkorder',
                    'quantityinshipping',
                    'totalwarehousevalue',
                    'costcalcqtycommitted',
                    'costcalccostcommitted',
                    'datecreated',
                    'timecreated',
                    'usercreatedkey',
                    'dateupdated',
                    'timeupdated',
                    'userupdatedkey',
                    'lastphysicalcountdate'
                    )

class LotNumRecordSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = LotNumRecord
        fields = ('part_number',
                    'description',
                    'lot_number',
                    'lot_quantity',
                    'date_created',
                    'line'
                    )

class PoPurchaseOrderDetailSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = PoPurchaseOrderDetail
        fields =('purchaseorderno',
                    'linekey',
                    'lineseqno',
                    'itemcode',
                    'extendeddescriptionkey',
                    'itemtype',
                    'itemcodedesc',
                    'usetax',
                    'requireddate',
                    'vendorpricecode',
                    'purchasesacctkey',
                    'valuation',
                    'unitofmeasure',
                    'warehousecode',
                    'productline',
                    'masterlinekey',
                    'reschedule',
                    'jobno',
                    'costcode',
                    'costtype',
                    'receiptofgoodsupdated',
                    'workorderno',
                    'stepno',
                    'substepprefix',
                    'substepsuffix',
                    'workordertype',
                    'allocatelandedcost',
                    'vendoraliasitemno',
                    'taxclass',
                    'commenttext',
                    'assetaccount',
                    'assettemplate',
                    'weightreference',
                    'weight',
                    'quantityordered',
                    'quantityreceived',
                    'quantitybackordered',
                    'masteroriginalqty',
                    'masterqtybalance',
                    'masterqtyorderedtodate',
                    'quantityinvoiced',
                    'unitcost',
                    'originalunitcost',
                    'extensionamt',
                    'receivedamt',
                    'invoicedamt',
                    'unitofmeasureconvfactor',
                    'receivedallocatedamt',
                    'invoicedallocatedamt',
                    'salesorderno',
                    'customerpono',
                    'purchaseorderhistorydtlseqno',
                    'workticketkey',
                    'workticketsteplinekey',
                    'workticketlinekey',
                    'workticketstatus'
                    )

class TimetableRunDataSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = TimetableRunData
        fields =('id',
                    'id2',
                    'bill_no',
                    'blend_pn',
                    'blend_desc',
                    'adjustedrunqty',
                    'qtyonhand',
                    'starttime',
                    'prodline',
                    'oh_after_run',
                    'week_calc'
                    )

class UpcomingBlendCountSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = UpcomingBlendCount
        fields = ('id',
                    'blend_pn',
                    'blend_desc',
                    'expected_on_hand',
                    'starttime',
                    'prodline',
                    )