from django.urls import path, include
from core import consumers
from core.views import api, web
from core.websockets import websocket_testing
from core.services import blend_scheduling_services, ghs_labels_services, foam_factors_services, forklift_checklist_services, pystray_services, label_printing_services, operating_supplies_services, manual_gauge_services
from core.services import inventory_services, tank_levels_services, lot_numbers_services, reports_services
from core.selectors import alerts_selectors, production_planning_selectors
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()

urlpatterns = [
    path('api/', include(router.urls)),
    path('forklift-checklist/', web.display_forklift_checklist, name='forklift-checklist'),
    path('blend-shortages/', web.display_blend_shortages, name='blend-shortages'),
    path('lot-num-records/', web.display_lot_num_records, name='display-lot-num-records'),
    path('timestudies/', web.display_timestudy_entry, name='display-timestudies'),
    path('timestudies/report/', web.display_timestudy_report, name='timestudy-report'),
    path('reports/', web.display_report_center, name='report-center'),
    path('blend-costing-report/', web.display_blend_costing_report, name='blend-costing-report'),
    path('blend-protection-audit/', web.display_blend_protection_audit, name='blend-protection-audit'),
    path('blend-protection-audit/run-uv-freeze/', web.trigger_uv_freeze_audit, name='run-uv-freeze-audit'),
    path('blend-schedule/', web.display_blend_schedule, name='blend-schedule'),
    path('issue-sheets/<prod_line>/<issue_date>', web.display_issue_sheets, name='issue-sheets'),
    path('batch-issue-table/<prod_line>/<issue_date>', web.display_batch_issue_table, name='batch-issue-table'),
    path('items-by-audit-group', web.display_items_by_audit_group, name='items-by-audit-group'),
    path('upcoming-blend-counts/', web.display_upcoming_blend_counts, name='upcoming-blend-counts'),
    path('upcoming-component-counts/', web.display_upcoming_component_counts, name='upcoming-component-counts'),
    path('count-list/display/', web.display_count_list, name='display-count-list'),
    path('display-count-report/', web.display_count_report, name='display-finished-counts'),
    path('display-count-collection-links/', web.display_count_collection_links, name='display-count-collection-links'),
    path('count-records/', web.display_count_records, name='display-count-records'),
    path('list-to-count-list/', web.display_list_to_count_list, name='list-to-count-list'),
    path('production-blend-runs/', web.display_all_upcoming_production, name='production-blend-runs'),
    path('bom-cost-tool/', web.display_bom_cost_tool, name='bom-cost-tool'),
    path('sales-order-vs-bom-cost/', web.display_sales_order_vs_bom_cost_report, name='sales-order-vs-bom-cost'),
    path('cost-impact-report/', web.display_cost_impact_report, name='cost-impact-report'),
    path('chemical-shortages/', web.display_chem_shortages, name='all-chem-shortages'),
    path('lookup-location/', web.display_lookup_location, name='lookup-location'),
    path('lookup-lot-numbers/', web.display_lookup_lot_numbers, name='lookup-lotnums'),
    path('lookup-item-quantity/', web.display_lookup_item_quantity, name='lookup-item'),
    path('tank-levels/', web.display_tank_levels, name='tank-levels'),
    path('tank-levels/msr/', web.display_tank_levels, name='tank-levels-msr'),
    path('manual-gauges/', web.display_manual_gauge_entries, name='manual-gauges'),
    path('manual-gauges/overview/', web.display_manual_gauge_overview, name='manual-gauges-overview'),
    path('checklist-management/', web.display_checklist_mgmt_page, name='display-checklist-mgmt-page'),
    path('purchasing-alias-audit/', web.display_purchasing_alias_audit, name='purchasing-alias-audit'),
    path('blend-statistics/', web.display_blend_statistics, name='display-blend-statistics'),
    path('max-producible-quantity/', web.display_maximum_producible_quantity, name='display-maximum-producible-quantity'),
    path('subcomponent-shortages/', web.display_subcomponent_shortages, name='subcomponent-shortages'),
    path('display-this-issue-sheet/<prod_line>/<item_code>', web.display_this_issue_sheet, name='display-this-issue-sheet'),
    path('display-adjustment-statistics/<filter_option>', web.display_adjustment_statistics, name='display-adjustment-statistics'),
    path('display-item-locations', web.display_all_item_locations, name='display-item-locations'),
    path('display-forklift-issues', web.display_forklift_issues, name='display-forklift-issues'),
    path('display-loop-status', web.display_loop_status, name='display-loop-status'),
    path('function-toggles/', web.display_function_toggles, name='function-toggles'),
    path('foam-factors/', web.display_foam_factors, name='display-foam-factors'),
    path('display-ghs-label-search', web.display_ghs_label_search, name='display-ghs-label-search'),
    path('display-ghs-label/<encoded_item_code>', web.display_ghs_label, name='display-ghs-label'),
    path('display-all-GHS-pictograms/', web.display_all_ghs_pictograms, name='display-all-GHS-pictograms'),
    path('display-blend-tote-label/', web.display_blend_tote_label, name='display-blend-id-label'),
    path('truck-rail-material-schedule/', web.display_truck_rail_material_schedule, name='truck-rail-material-schedule'),
    path('component-stock-coverage/', web.display_component_stock_after_orders, name='component-stock-coverage'),
    path('component-stock-coverage/data/', web.get_component_stock_after_orders_data, name='component-stock-coverage-data'),
    path('display-partial-container-label/', web.display_partial_container_label, name='partial-container-label'),
    path('display-missing-audit-groups/', web.display_missing_audit_groups, name='display-missing-audit-groups'),
    path('orphaned-lots/', web.display_orphaned_lots, name='display-orphaned-lots'),
    path('display-raw-material-label', web.display_raw_material_label, name='display-raw-material-label'),
    path('partial-container-label/', web.display_partial_container_label, name='partial-container-label'),
    path('display-flush-tote-label/', web.display_flush_tote_label, name='display_flush_tote_label'),
    path('tank-level-change-report/', web.display_tank_level_change_report, name='tank-level-change-report'),
    path('test-page/', web.display_test_page, name='test-page'),
    path('excess-blends/', web.display_excess_blends, name='excess-blends'),
    path('blend-item-status/', web.display_blend_item_status, name='blend-item-status'),
    path('xmr-tank-control-limits/', web.display_xmr_tank_control_limits, name='xmr-tank-control-limits'),
    path('tank-usage/<str:tank_identifier>/', web.display_tank_usage_monitor, name='tank-usage-monitor'),
    path('purchasing-aliases/', web.display_all_purchasing_aliases, name='display_all_purchasing_aliases'),
    path('container-classifications/', web.display_container_classifications, name='display_container_classifications'),
    path('flush-tote-entry/', web.flush_tote_entry_view, name='flush-tote-entry'),
    path('flush-tote-records/', web.flush_totes_view, name='flush-tote-records'),
    path('production-holidays/', web.display_production_holidays, name='production-holidays'),
    path('desk-labor-rates/', web.display_desk_labor_rates, name='desk-labor-rates'),

    path('add-lot-num-record/', lot_numbers_services.add_lot_num_record, name='add-lot-num-record'),
    path('update-lot-num-record/<lot_num_id>', lot_numbers_services.update_lot_num_record, name='update-lot-num-record'),
    path('delete-lot-num-records/<records_to_delete>', lot_numbers_services.delete_lot_num_records, name='delete-lot-num-records'),
    path('get-lot-num-record-row/<int:lot_id>/', lot_numbers_services.get_rendered_lot_row, name='get-lot-num-record-row'),
    path('create-report/<which_report>', web.display_report, name='reports'),
    path('schedule-management-request/<request_type>/<blend_area>/<blend_id>', blend_scheduling_services.manage_blend_schedule, name='schedule-management'),
    path('move-blend-with-tank-selection/', blend_scheduling_services.move_blend_with_tank_selection, name='move-blend-with-tank-selection'),
    path('add-item-to-new-group', inventory_services.add_item_to_new_group, name='add-item-to-new-group'),
    path('count-list/add/', inventory_services.add_count_list, name='add-count-list'),
    path('delete-count-collection-links/', inventory_services.delete_count_collection_links, name='delete-count-collection-links'),
    path('update-count-collection-link/', inventory_services.update_count_collection_link, name='update-count-collection-link'),
    path('create-automated-countlist/', inventory_services.create_automated_countlist, name='create-automated-countlist'),
    path('check-automated-count-exists/', inventory_services.check_automated_count_exists, name='check-automated-count-exists'),
    path('get-tank-levels/', tank_levels_services.get_tank_levels_html, name='get-tanks-html'),
    path('update-forklift-submission-tracker/', forklift_checklist_services.update_submission_tracker, name='update-submission-tracker'),
    path('email-submission-report/', forklift_checklist_services.email_submission_report, name='email-submission-report'),
    path('email-issue-report/', forklift_checklist_services.email_issue_report, name='email-issue-report'),
    path('update-item-location/<int:item_location_id>/', inventory_services.update_item_location, name='update-item-location'),
    path('add-missing-item-locations/', inventory_services.add_missing_item_locations, name='add-missing-item-locations'),
    path('update-desk-order/', blend_scheduling_services.update_desk_order, name='update-desk-order'),
    path('feedback/', web.feedback, name='feedback'),
    path('add-foam-factor/', foam_factors_services.add_foam_factor, name='add-foam-factor'),
    path('update-foam-factor/<foam_factor_id>', foam_factors_services.update_foam_factor, name='update-foam-factor'),
    path('delete-foam-factor/<foam_factor_id>', foam_factors_services.delete_foam_factor, name='delete-foam-factor'),
    path('delete-ghs-label', ghs_labels_services.delete_ghs_pictogram, name='delete-ghs-label'),
    path('update-ghs-label', ghs_labels_services.update_ghs_pictogram, name='update-ghs-label'),
    path('print-blend-label/', label_printing_services.print_blend_label, name='print-blend-label'),
    path('log-container-label-print/', label_printing_services.log_container_label_print, name='log-container-label-print'),
    path('update-collection-link-order/', inventory_services.update_collection_link_order, name='update-collection-link-order'),
    path('update-scheduled-blend-tank', blend_scheduling_services.update_scheduled_blend_tank, name='update-scheduled-blend-tank'),
    path('get-components-in-use-soon/', production_planning_selectors.get_components_in_use_soon, name='get-components-in-use-soon'),
    path('add-note-line-to-schedule/', blend_scheduling_services.add_note_line_to_schedule, name='add-note-line-to-schedule'),
    path('trigger-restart/', pystray_services.trigger_looper_restart, name='trigger_looper_restart'),
    path('get-pystray-service-status/', pystray_services.get_pystray_service_status, name='get-pystray-service-status'),
    path('get-data-looper-log/', pystray_services.get_data_looper_log, name='get-data-looper-log'),
    path('api/function-toggles/list/', pystray_services.list_function_toggles, name='function-toggle-list'),
    path('api/function-toggles/create/', pystray_services.create_function_toggle, name='function-toggle-create'),
    path('api/function-toggles/update/', pystray_services.update_function_toggle, name='function-toggle-update'),
    path('api/function-toggles/delete/', pystray_services.delete_function_toggle, name='function-toggle-delete'),
    path('api/flush-totes/', api.flush_tote_list_api, name='flush-tote-list-api'),
    path('api/flush-totes/<int:pk>/', api.flush_tote_detail_api, name='flush-tote-detail-api'),
    path('api/validate-blend-item/', api.validate_blend_item, name='validate-blend-item'),
    path('api/purchasing-alias-audit/', operating_supplies_services.update_purchasing_alias_audit, name='purchasing-alias-audit-api'),
    path('api/purchasing-alias/<int:alias_id>/', operating_supplies_services.update_purchasing_alias, name='update-purchasing-alias'),
    path('api/purchasing-alias/create/', operating_supplies_services.create_purchasing_alias, name='create-purchasing-alias'),
    path('api/purchasing-alias/<int:alias_id>/delete/', operating_supplies_services.delete_purchasing_alias, name='delete-purchasing-alias'),
    path('api/purchasing-alias/next-id/', api.get_next_purchasing_alias_id, name='next-purchasing-alias-id'),
    path('api/manual-gauge/<int:storage_tank_id>/', manual_gauge_services.update_manual_gauge, name='update-manual-gauge'),
    path('api/container-classification/<int:classification_id>/', operating_supplies_services.update_container_classification, name='update-container-classification'),
    path('api/container-classification/create/', operating_supplies_services.create_container_classification, name='create-container-classification'),
    path('api/container-classification/<int:classification_id>/delete/', operating_supplies_services.delete_container_classification, name='delete-container-classification'),
    path('api/container-classification/next-id/', api.get_next_container_classification_id, name='next-container-classification-id'),
    path('api/cache-health/', pystray_services.cache_health, name='cache_health'),
    path('api/log-tank-usage/', tank_levels_services.log_tank_usage, name='log_tank_usage'),
    path('print_blend_sheet/', pystray_services.print_blend_sheet, name='print_blend_sheet'),
    path('trigger-excel-macro-execution/', pystray_services.trigger_excel_macro_execution, name='trigger_excel_macro_execution'),
    path('test-websocket/', websocket_testing.test_websocket_send, name='test-websocket'),
    path('active-formula-change-alerts/', alerts_selectors.get_active_formula_change_alerts, name='get_active_formula_change_alerts'),

    path('forklift-serial-request/', api.get_json_forklift_serial, name='get-forklift-serial'),
    path('get-latest-lot-num-record/', api.get_json_latest_lot_num_record, name='get-latest-lot-num-record'),
    path('get-json-lot-details/<int:lot_id>/', api.get_json_lot_details, name='get-json-lot-details'),
    path('get-json-lot-details-by-number/', api.get_json_lot_details_by_number, name='get-json-lot-details-by-number'),
    path('lot-num-records/<int:lot_id>/timestudy/', api.update_lot_timestudy, name='update-lot-timestudy'),
    path('get-json-counting-unit/', api.get_json_counting_unit, name='get-json-counting-unit'),
    path('get-json-containers-from-count/', api.get_json_containers_from_count, name='get-json-containers-from-count'),
    path('item-location-request/', api.get_json_item_location, name='get-item-location'),
    path('item-info-request/', api.get_json_item_info, name='item-info-request'),
    path('get-tank-specs/', api.get_json_tank_specs, name='get-tank-specs'),
    path('get-BOM-fields/', api.get_json_bill_of_materials_fields, name='get-json-bom-fields'),
    path('get-max-producible-quantity/<lookup_value>', api.get_json_get_max_producible_quantity, name='get-json-max-producible-quantity'),
    path('get-refresh-status/', api.get_json_refresh_status, name='get-refresh-status'),
    path('api/loop-status/', api.get_json_loop_status_detail, name='api-loop-status-detail'),
    path('get-current-user-initials/', api.get_json_current_user_initials, name='get-current-user-initials'),
    path('get-all-GHS-fields/', api.get_json_all_ghs_fields, name='get-all-GHS-fields'),
    path('get-json-lot-number/', api.get_json_lot_number, name='get-json-lot-number'),
    path('get-json-most-recent-lot-records/', api.get_json_most_recent_lot_records, name='get-json-most-recent-lot-records'),
    path('get-json-container-label-data/', api.get_json_container_label_data, name='get-json-container-label-data'),
    path('get-json-all-container-labels-data/', api.get_json_all_container_labels_data, name='get-json-all-container-labels-data'),
    path('get-json-all-blend-qtyperbill/', api.get_json_all_blend_qtyperbill, name='get-all-blend-qtyperbill'),
    path('api/bom-cost/', api.get_json_bom_cost, name='bom-cost'),
    path('api/sales-order-bom-cost/', api.get_json_sales_order_vs_bom_cost, name='sales-order-bom-cost'),
    path('api/cost-impact-analysis/', api.get_json_cost_impact_analysis, name='cost-impact-analysis'),
    path('api/misc-report-types/', api.get_json_misc_report_types, name='misc-report-types'),
    path('get-tote-classification-data/', api.get_tote_classification_data, name='get-tote-classification-data'),
    path('get-json-matching-lot-numbers/', api.get_json_matching_lot_numbers, name='get-json-matching-lot-numbers'),
    path('api/get-single-tank-level/<str:tank_identifier>/', api.get_json_single_tank_level, name='get-single-tank-level'),
    path('get-all-foam-factors/', api.get_json_all_foam_factors, name='get-json-all-foam-factors'),
    path('api/projected-production-datetime/', api.get_projected_production_datetime, name='projected-production-datetime'),
    path('api/blend-shortage-times/', api.get_json_blend_shortage_times, name='blend-shortage-times'),
    path('api/production-holiday/', api.get_json_production_holidays, name='get-production-holidays'),
    path('api/production-holiday/create/', api.create_json_production_holiday, name='create-production-holiday'),
    path('api/production-holiday/<int:holiday_id>/', api.update_json_production_holiday, name='update-production-holiday'),
    path('api/production-holiday/<int:holiday_id>/delete/', api.delete_json_production_holiday, name='delete-production-holiday'),
    path('api/desk-labor-rates/', api.get_json_desk_labor_rates, name='api-desk-labor-rates'),
    path('api/desk-labor-rates/update/', api.update_json_desk_labor_rate, name='api-desk-labor-rate-update'),
]

websocket_urlpatterns = [
    path('ws/count_collection/', consumers.CountCollectionConsumer.as_asgi()),
    path('ws/count_list/', consumers.CountCollectionConsumer.as_asgi()),
]

urlpatterns += websocket_urlpatterns
