from django.urls import path, include
from core import views
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('api/', include(router.urls)),
    path('forklift-checklist/', views.display_forklift_checklist, name='forklift-checklist'),
    path('forklift-serial-request/', views.get_json_forklift_serial, name='get-forklift-serial'),
    path('blend-shortages/', views.display_blend_these, name='blend-shortages'),
    path('lot-num-records/', views.display_lot_num_records, name='display-lot-num-records'),
    path('add-lot-num-record/', views.add_lot_num_record, name='add-lot-num-record'),
    path('update-lot-num-record/<lot_num_id>', views.update_lot_num_record, name='update-lot-num-record'),
    path('delete-lot-num-records/<records_to_delete>', views.delete_lot_num_records, name='delete-lot-num-records'),
    path('blend-sheet/<lot>/', views.display_blend_sheet, name='blend-sheet'),
    path('blend-sheet-complete/', views.display_conf_blend_sheet_complete, name='blend-sheet-complete'),
    path('reports/', views.display_report_center, name='report-center'),
    path('create-report/<which_report>/<item_code>', views.create_report, name='reports'),
    path('add-desk-one-schedule-item/', views.add_deskone_schedule_item, name='add-lot-to-deskone-schedule'),
    path('add-desk-two-schedule-item/', views.add_desktwo_schedule_item, name='add-lot-to-desktwo-schedule'),
    path('blend-schedule/', views.display_blend_schedule, name='blend-schedule'),
    path('schedule-management-request/<request_type>/<blend_area>/<blend_id>/<blend_list_position>', views.manage_blend_schedule, name='schedule-management'),
    path('batch-issue-table/<line>', views.display_batch_issue_table, name='batch-issue-table'),
    path('issue-sheets/<prod_line>/<issue_date>', views.display_issue_sheets, name='issue-sheets'),
    path('upcoming-blend-counts/', views.display_upcoming_blend_counts, name='upcoming-blend-counts'),
    path('upcoming-component-counts/', views.display_upcoming_component_counts, name='upcoming-component-counts'),
    path('count-list/add/<encoded_item_code_list>/<encoded_pk_list>', views.add_count_list, name='add-count-list'),
    path('count-list/display/<encoded_pk_list>', views.display_count_list, name='display-count-list'),
    path('display-finished-counts/<encoded_pk_list>', views.display_count_report, name='display-finished-counts'),
    path('delete-count-record/<redirect_page>/<items_to_delete>/<all_items>', views.delete_count_record, name='delete-count-record'),
    path('count-records/', views.display_count_records, name='display-count-records'),
    path('production-blend-runs/', views.display_all_upcoming_production, name='production-blend-runs'),
    path('chemical-shortages/', views.display_chem_shortages, name='all-chem-shortages'),
    path('item-location-request/', views.get_json_item_location, name='get-item-location'),
    path('item-info-request/', views.get_json_item_info, name='item-info-request'),
    path('lookup-location/', views.display_lookup_location, name='lookup-location'),
    path('lookup-lot-numbers/', views.display_lookup_lot_numbers, name='lookup-lotnums'),
    path('lookup-item-quantity/', views.display_lookup_item_quantity, name='lookup-item'),
    path('tank-levels/', views.display_tank_levels, name='tank-levels'),
    path('get-tank-specs/', views.get_json_tank_specs, name='get-tank-specs'),
    path('get-tank-levels/', views.get_tank_levels_html, name='get-tanks-html'),
    path('get-BOM-fields/', views.get_json_bill_of_materials_fields, name='get-json-bom-fields'),
    path('checklist-management/', views.display_checklist_mgmt_page, name='display-checklist-mgmt-page'),
    path('update-forklift-submission-tracker/', views.update_submission_tracker, name='update-submission-tracker'),
    path('email-submission-report/', views.email_submission_report, name='email-submission-report'),
    path('email-issue-report/', views.email_issue_report, name='email-issue-report'),
    path('blend-statistics/', views.display_blend_statistics, name='display-blend-statistics'),
    path('get-max-producible-quantity/<lookup_value>', views.get_json_get_max_producible_quantity, name='get-json-max-producible-quantity'),
    path('max-producible-quantity/', views.display_maximum_producible_quantity, name='display-maximum-producible-quantity'),
    path('component-shortages/', views.display_component_shortages, name='component-shortages'),
    path('subcomponent-shortages/', views.display_subcomponent_shortages, name='subcomponent-shortages'),
    path('test-page/', views.display_test_page, name='test-page'),
]