from django.urls import path, include
from core import views
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest-framework')),
    path('forkliftchecklist/', views.display_forklift_checklist, name='forklift-checklist'),
    path('forkliftchecklist/forklift_serial_request/', views.get_json_forklift_serial, name='get-forklift-serial'),
    path('blendshortages/', views.display_blend_these, name='blend-shortages'),
    path('lotnumrecords/', views.display_lot_num_records, name='display-lot-num-records'),
    path('addlotnumrecord/', views.add_lot_num_record, name='add-lot-num-record'),
    path('updatelotnumrecord/<lot_num_id>', views.update_lot_num_record, name='update-lot-num-record'),
    path('deletelotnumrecords/<records_to_delete>', views.delete_lot_num_records, name='delete-lot-num-records'),
    path('blendsheet/<lot>/', views.display_blend_sheet, name='blendsheet'),
    path('blendsheetcomplete/', views.display_conf_blend_sheet_complete, name='blend-sheet-complete'),
    path('blendsheet/', views.display_blend_sheet, name='blendsheet'),
    path('reports/', views.display_report_center, name='report-center'),
    path('reports/<which_report>/<item_code>', views.display_report, name='report'),
    path('adddeskonescheduleitem/', views.add_deskone_schedule_item, name='add-lot-to-deskone-schedule'),
    path('adddesktwoscheduleitem/', views.add_desktwo_schedule_item, name='add-lot-to-desktwo-schedule'),
    path('blendschedule/<blendarea>', views.display_blend_schedule, name='blend-schedule'),
    path('mngReq/<request_type>/<blend_area>/<blend_id>/<blend_list_position>', views.manage_blend_schedule, name='schedule-manager'),
    path('batchIssueTable/<line>', views.display_batch_issue_table, name='batch-issue-table'),
    path('issuesheets/<prod_line>/<issue_date>', views.display_issue_sheets, name='issue-sheets'),
    path('blendcountsheets/', views.display_upcoming_counts, name='upcoming-counts'),
    path('countlist/add/<encoded_item_code_list>/<encoded_pk_list>', views.add_count_list, name='add-count-list'),
    path('countlist/display/<encoded_pk_list>', views.display_count_list, name='display-count-list'),
    path('displayfinishedcounts/<encoded_pk_list>', views.display_count_report, name='display-finished-counts'),
    path('delete_countrecord/<redirect_page>/<items_to_delete>/<all_items>', views.delete_count_record, name='delete-count-record'),
    path('countrecords/', views.display_count_records, name='display-count-records'),
    path('productionblendruns/', views.display_all_upcoming_production, name='production-blend-runs'),
    path('chemshortages/', views.display_chem_shortages, name='all-chem-shortages'),
    path('item_location_request/', views.get_json_item_location, name='get-item-location'),
    path('item_info_request/', views.get_json_item_info, name='item-info-request'),
    path('lookuplocation/', views.display_lookup_location, name='lookup-location'),
    path('lookuplotnum/', views.display_lookup_lotnums, name='lookup_lotnums'),
    path('tanklevels/', views.display_tank_levels, name='tank-levels'),
    path('gettankspecs/', views.get_json_tank_specs, name='get-tank-specs'),
    path('gettanklevels/', views.get_tank_levels_html, name='get-tanks-html'),
    path('getBOMfields/', views.get_json_bill_of_materials_fields, name='get-json-bom-fields'),
    path('checklistmgmt/', views.display_checklist_mgmt_page, name='display-checklist-mgmt-page'),
    path('updateforkliftsubtracker/', views.update_submission_tracker, name='update-submission-tracker'),
    path('emailsubmissionreport/', views.email_submission_report, name='email-submission-report'),
    path('emailissuereport/', views.email_issue_report, name='email-issue-report'),
    path('blendstatistics/', views.display_blend_statistics, name='display-blend-statistics'),
    path('testpage/', views.display_test_page, name='test-page'),
]